### ISSUE TITLE
steelpenny service PID file needs to be renamed

### ISSUE THREAD

**Issue by zombieprocess** [MRN-Code/quarterback#97]
`/var/run/coins-node-api.pid` => `/var/run/steelpenny.pid`

The startup configs will also need to be updated to reflect the change in MRN-Code/ansible-ops

**Comment by zombieprocess** [comment]
Looking into this further, it kinda looks like `steelpenny` itself does not generate the PID file, so I should be able to change it in the `ansible-ops` side, with the startup configs.

**Comment by swashcap** [comment]
> Looking into this further, it kinda looks like `steelpenny` itself does not generate the PID file

`ag`-ing around steelpenny’s source doesn’t reveal any PID stuff at all. Looks like it’s entirely in _ansible_ops_: https://github.com/MRN-Code/ansible-ops/blob/master/roles/steelpenny/templates/upstart.j2

**Comment by zombieprocess** [comment]
cool, we can probably close this issue here then.
